---
- hosts: suse
  remote_user: root
  tasks:
    - name: "install service script"
      copy:
        src: "netns-umount.sh"
        dest: "/usr/local/bin/"
        mode: 0755
    - name: "install service file"
      copy:
        src: "netns-umount.service"
        dest: "/etc/systemd/system/"
        mode: 0644
    - name: "activate netns-umount.service"
      systemd: state=started enabled=yes name=netns-umount daemon_reload=yes
