#!/bin/bash

#TODO: read swapiness from config
value="40"

find /sys/fs/cgroup/memory -type f -name "memory.swappiness" | while read -r target; do
  echo "processing $target"
  echo "$value" >"$target"
done
